services:
    a:
        # Build our go application with hostname "a", 
        # this is also our entry point as its is mapped to an external port
        build: ../.
        image: PETS/app_v1
        container_name: serverA
        ports:
            - "80:80"
        volumes:
            - ./../Example Data/Server A/Example Data_A.ttl:/usr/app/shared_volume/data.ttl
            # - ../src/:/usr/app
    b:
        # same as a but no contact to outside
        image: PETS/app_v1
        container_name: serverB
        volumes:
            - ./../Example Data/Server B/Example Data_B.ttl:/usr/app/shared_volume/data.ttl
            # - ../src/:/usr/app
    c:

        # same as a but no contact to outside
        image: PETS/app_v1
        container_name: serverC
        volumes:
            - ./../Example Data/Server C/Example Data_C.ttl:/usr/app/shared_volume/data.ttl
volumes:
    dataA:
    dataB:
    dataC: