services:
    a:
        # Build our go application with hostname "a", 
        # this is also our entry point as its is mapped to an external port
        build: ../.
        image: PETS/app_v1
        container_name: serverA
        ports:
            - "80:80"
        volumes:
            - /usr/app/Example Data/Server A:/usr/app/shared_volume
            # - ../src/:/usr/app
    b:
        # same as a but no contact to outside
        image: PETS/app_v1
        container_name: serverB
        volumes:
            - /usr/app/"Example Data"/"Server B"/usr/app/shared_volume
            # - ../src/:/usr/app
    c:

        # same as a but no contact to outside
        image: PETS/app_v1
        container_name: serverC
        volumes:
            - /usr/app/"Example Data"/"Server C":/usr/app/shared_volume
volumes:
    dataA:
    dataB:
    dataC: